name: GitVerse CI/CD
# on:
#   push:
#     branches: [trunk/*]
#   pull_request:
#     branches: [trunk/*]
jobs:
  check:
    name: Auto tests
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Display event name
        run: echo ${{ gitverse.event_name }}
      - name: Display Workflow
        run: echo ${{ gitverse.workflow }}
      - name: Display repository name
        run: echo ${{ gitverse.Repository }}
      - name: Display repository owner
        run: echo ${{ gitverse.repository_owner }}
      - name: Display actor
        run: echo ${{ gitverse.actor }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          npm run test:browser -- --run
          npm run test:node -- --run
      - name: Check code style
        run: npm run lint
